### ISSUE TITLE
GUI crashes if time range does not start at 0

### ISSUE THREAD

**Issue by czuba** [MouseLand/Kilosort2#110] opened 2019-09-09 22:48 UTC
GUI crashes in `predictData.m` while matching up spike times with batch number when sort does not start from the beginning of the raw data file.
`ks.ops.trange(1) ~= 0`

**Comment by marius10p** [comment] 2019-09-20 13:49
@nsteinme any ideas?

**Comment by nsteinme** [comment] 2019-09-24 07:33
Yes that sounds like my fault, I don't think I tested this condition. Will
find time to take a look... @czuba if you think you can identify the fix
and want to make a PR that would be great.

**Comment by nsteinme** [comment] 2019-10-06 20:39
I could not reproduce this. @czuba I think you may have had a crash for a different reason? It appears to work fine for me with trange(1)~=0. If you can report the error message or a minimal example or something, please re-open. Closing for now.

**Closed by nsteinme** 2019-10-06 20:39 UTC

**Comment by YuelinS** [comment] 2020-12-18 04:21
Hi @nsteinme, I seemed to run into the same issue, error occurred after I set the time range to [10000 Inf] in the GUI.

Here is the error message:

Index in position 2 exceeds array bounds (must not exceed 216).
Error in predictData (line 24)
    ampi = rez.muA(inclTemps(s), ibatch);
Error in ksGUI/updateDataView (line 890)
                        pd = predictData(obj.rez, samps);
Error in ksGUI/timeClickCB (line 1426)
                obj.updateDataView;
Error in ksGUI>@(f,k)obj.timeClickCB(f,k) (line 399)
            set(obj.H.timeBckg, 'ButtonDownFcn', @(f,k)obj.timeClickCB(f,k));
24      ampi = rez.muA(inclTemps(s), ibatch);

Also, the prediction is all flat in the GUI data window, yet I can see predicted spikes in the Phy GUI. I'm not sure if this is related.

**Comment by marius10p** [comment] 2020-12-18 04:46
The time range is in seconds, does your data have more than 10,000 seconds?

**Comment by YuelinS** [comment] 2020-12-18 06:04
Thanks for the prompt reply, yes indeed, it's a 4-hour recording.

**Comment by marius10p** [comment] 2020-12-19 14:09
Hmm, then it looks like a GUI thing. Let's wait until @nsteinme has time to test it again in Kilosorr 2.5.

**Comment by YuelinS** [comment] 2020-12-19 22:47
Ok, much appreciated!
